;;  Copyright (c) Rich Hickey. All rights reserved.
;;  The use and distribution terms for this software are covered by the
;;  Eclipse Public License 1.0 (http://opensource.org/licenses/eclipse-1.0.php)
;;  which can be found in the file epl-v10.html at the root of this distribution.
;;  By using this software in any fashion, you are agreeing to be bound by
;;  the terms of this license.
;;  You must not remove this notice, or any other, from this software.

(ns ^{:doc "Receive - Eval - Print - Loop

  Receive a block of JS (presumably generated by a ClojureScript compiler)
  Evaluate it naively
  Print the result of evaluation to a string
  Send the resulting string back to the server Loop!"}
  clojure.browser.ws
  (:require [goog.dom :as gdom]
            [clojure.browser.event :as event :refer [event-types]]
            [clojure.browser.net :as net]
            [clojure.browser.repl :as brepl]
            [cljs.reader :as reader :refer [read-string]]))

(def ws-conn (atom nil))
(def last-repl (atom nil))

(defn repl-print
  "Send data to be printed in the REPL"
  [& args]
  (if-let [conn @ws-conn]
    (net/transmit conn {:op :print
                        :value {:status :success
                                :repl @last-repl
                                :value (apply pr-str args)}})))

(defn console-print [& args]
  "Print data to the javascript console"
  (.apply (.-log js/console) js/console (into-array args)))

(def print-fns
  {:repl repl-print
   :console console-print
   #{:repl :console} (fn [& args]
                       (apply console-print args)
                       (apply repl-print args))})

(defn alive? []
  "Returns truthy value if the REPL is attempting to connect or is
   connected, or falsy value otherwise."
  (not (nil? @ws-conn)))

(defmulti ws-msg
  "Process messages from WebSocket server"
  {:arglists '([msg])}
  :op)

(defmethod ws-msg
  :error
  [msg]
  (.error js/console (str "Websocket REPL error " (:type msg))))

(defmethod ws-msg
  :eval-js
  [msg]
  (let [{:keys [code repl]} msg]
    (when repl (reset! last-repl repl))
    {:op :result
     :value (try
              {:status :success
               :repl repl
               :value (str (js* "eval(~{code})"))}
              (catch :default e
                {:status :exception
                 :repl repl
                 :ua-product (brepl/get-ua-product)
                 :value (pr-str e)
                 :stacktrace (if (.hasOwnProperty e "stack")
                               (.-stack e)
                               "No stacktrace available.")}))}))

(defn connect
  "Connects to a WebSocket REPL server from an HTML document. After the
  connection is made, the REPL will evaluate forms in the context of
  the document that called this function."
  [ws-url & {:keys [verbose on-open on-error on-close print]
             :or {verbose false print :repl}}]
  (let [repl (net/websocket-connection)]
    (swap! ws-conn (constantly repl))
    (event/listen repl :opened
      (fn [evt]
        (set-print-fn! repl-print #_ (if (fn? print) print (get print-fns print)))
        (set-print-err-fn! repl-print)
        (net/transmit repl (pr-str {:op :ready
                                    :value {:status :success
                                            :repl @last-repl}}))
        (when verbose (.info js/console "Opened Websocket REPL connection"))
        (when (fn? on-open) (on-open))))
    (event/listen repl :message
      (fn [evt]
        (let [msg (read-string (.-message evt))
              response (-> msg ws-msg pr-str)]
          (net/transmit repl response))))
    (event/listen repl :closed
      (fn [evt]
        (reset! ws-conn nil)
        (when verbose (.info js/console "Closed Websocket REPL connection"))
        (when (fn? on-close) (on-close))))
    (event/listen repl :error
      (fn [evt]
        (when verbose (.error js/console "WebSocket error" evt))
        (when (fn? on-error) (on-error evt))))
    (net/connect repl ws-url)))
